"""initial schema

Revision ID: 2575703c0c0e
Revises: 
Create Date: 2026-05-29 22:43:04.952935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2575703c0c0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('metro_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighbourhood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('coord_source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('neighbourhood_metro',
    sa.Column('neighbourhood_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['metro_station.id'], ),
    sa.PrimaryKeyConstraint('neighbourhood_id', 'station_id')
    )
    op.create_table('price_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neighbourhood_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Text(), nullable=True),
    sa.Column('price_eur', sa.Numeric(), nullable=True),
    sa.Column('price_bgn', sa.Numeric(), nullable=True),
    sa.Column('price_eur_sqm', sa.Numeric(), nullable=True),
    sa.Column('price_bgn_sqm', sa.Numeric(), nullable=True),
    sa.Column('overall_avg_eur_sqm', sa.Numeric(), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_snapshot')
    op.drop_table('neighbourhood_metro')
    op.drop_table('neighbourhood')
    op.drop_table('metro_station')
    op.drop_table('city')
    # ### end Alembic commands ###
