"""builder, new_building, new_building_source, crawl_run tables

Revision ID: 3d5c4a6ebfcd
Revises: 8aefbaffe800
Create Date: 2026-05-31 08:56:00.902110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5c4a6ebfcd'
down_revision: Union[str, Sequence[str], None] = '8aefbaffe800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eik', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_form', sa.Text(), nullable=True),
    sa.Column('hq_city_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('capital_bgn', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('owners', sa.JSON(), nullable=True),
    sa.Column('managers', sa.JSON(), nullable=True),
    sa.Column('financials', sa.JSON(), nullable=True),
    sa.Column('ksb_category', sa.Text(), nullable=True),
    sa.Column('ksb_active', sa.Boolean(), nullable=True),
    sa.Column('insolvency_flag', sa.Boolean(), nullable=True),
    sa.Column('tax_debt_bgn', sa.Numeric(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hq_city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builder_eik'), 'builder', ['eik'], unique=True)
    op.create_table('crawl_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.BigInteger(), nullable=False),
    sa.Column('records_parsed', sa.Integer(), nullable=False),
    sa.Column('records_emitted', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Numeric(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('neighbourhood_id', sa.Integer(), nullable=True),
    sa.Column('canonical_key', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=True),
    sa.Column('developer_name', sa.Text(), nullable=True),
    sa.Column('akt_stage', sa.Text(), nullable=True),
    sa.Column('completion_year', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('price_eur_sqm', sa.Numeric(), nullable=True),
    sa.Column('area_min_sqm', sa.Numeric(), nullable=True),
    sa.Column('area_max_sqm', sa.Numeric(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['builder.id'], ),
    sa.ForeignKeyConstraint(['neighbourhood_id'], ['neighbourhood.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_building_canonical_key'), 'new_building', ['canonical_key'], unique=True)
    op.create_table('new_building_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_building_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('price_eur_sqm', sa.Numeric(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_building_id'], ['new_building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_building_source')
    op.drop_index(op.f('ix_new_building_canonical_key'), table_name='new_building')
    op.drop_table('new_building')
    op.drop_table('crawl_run')
    op.drop_index(op.f('ix_builder_eik'), table_name='builder')
    op.drop_table('builder')
    # ### end Alembic commands ###
